// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bank_accounts.sql

package sqlcdb

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createBankAccount = `-- name: CreateBankAccount :one
INSERT INTO
    bank_accounts (
        item_id,
        plaid_account_id,
        account_name,
        official_name,
        account_type,
        account_subtype,
        current_balance,
        available_balance,
        iso_currency_code
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9
    )
RETURNING
    id, item_id, plaid_account_id, account_name, official_name, account_type, account_subtype, current_balance, available_balance, iso_currency_code, updated_at
`

type CreateBankAccountParams struct {
	ItemID           uuid.UUID
	PlaidAccountID   string
	AccountName      string
	OfficialName     sql.NullString
	AccountType      string
	AccountSubtype   sql.NullString
	CurrentBalance   string
	AvailableBalance string
	IsoCurrencyCode  string
}

func (q *Queries) CreateBankAccount(ctx context.Context, arg CreateBankAccountParams) (BankAccount, error) {
	row := q.db.QueryRowContext(ctx, createBankAccount,
		arg.ItemID,
		arg.PlaidAccountID,
		arg.AccountName,
		arg.OfficialName,
		arg.AccountType,
		arg.AccountSubtype,
		arg.CurrentBalance,
		arg.AvailableBalance,
		arg.IsoCurrencyCode,
	)
	var i BankAccount
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.PlaidAccountID,
		&i.AccountName,
		&i.OfficialName,
		&i.AccountType,
		&i.AccountSubtype,
		&i.CurrentBalance,
		&i.AvailableBalance,
		&i.IsoCurrencyCode,
		&i.UpdatedAt,
	)
	return i, err
}

const getBankAccountByID = `-- name: GetBankAccountByID :one
SELECT id, item_id, plaid_account_id, account_name, official_name, account_type, account_subtype, current_balance, available_balance, iso_currency_code, updated_at FROM bank_accounts WHERE id = $1
`

func (q *Queries) GetBankAccountByID(ctx context.Context, id uuid.UUID) (BankAccount, error) {
	row := q.db.QueryRowContext(ctx, getBankAccountByID, id)
	var i BankAccount
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.PlaidAccountID,
		&i.AccountName,
		&i.OfficialName,
		&i.AccountType,
		&i.AccountSubtype,
		&i.CurrentBalance,
		&i.AvailableBalance,
		&i.IsoCurrencyCode,
		&i.UpdatedAt,
	)
	return i, err
}

const getBankAccountByPlaidAccountID = `-- name: GetBankAccountByPlaidAccountID :one
SELECT id, item_id, plaid_account_id, account_name, official_name, account_type, account_subtype, current_balance, available_balance, iso_currency_code, updated_at FROM bank_accounts WHERE plaid_account_id = $1 LIMIT 1
`

func (q *Queries) GetBankAccountByPlaidAccountID(ctx context.Context, plaidAccountID string) (BankAccount, error) {
	row := q.db.QueryRowContext(ctx, getBankAccountByPlaidAccountID, plaidAccountID)
	var i BankAccount
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.PlaidAccountID,
		&i.AccountName,
		&i.OfficialName,
		&i.AccountType,
		&i.AccountSubtype,
		&i.CurrentBalance,
		&i.AvailableBalance,
		&i.IsoCurrencyCode,
		&i.UpdatedAt,
	)
	return i, err
}

const getBankAccountsByItemID = `-- name: GetBankAccountsByItemID :many
SELECT id, item_id, plaid_account_id, account_name, official_name, account_type, account_subtype, current_balance, available_balance, iso_currency_code, updated_at
FROM bank_accounts
WHERE
    item_id = $1
ORDER BY account_name
`

func (q *Queries) GetBankAccountsByItemID(ctx context.Context, itemID uuid.UUID) ([]BankAccount, error) {
	rows, err := q.db.QueryContext(ctx, getBankAccountsByItemID, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankAccount
	for rows.Next() {
		var i BankAccount
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.PlaidAccountID,
			&i.AccountName,
			&i.OfficialName,
			&i.AccountType,
			&i.AccountSubtype,
			&i.CurrentBalance,
			&i.AvailableBalance,
			&i.IsoCurrencyCode,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBankAccountsByUserID = `-- name: GetBankAccountsByUserID :many
SELECT ba.id, ba.item_id, ba.plaid_account_id, ba.account_name, ba.official_name, ba.account_type, ba.account_subtype, ba.current_balance, ba.available_balance, ba.iso_currency_code, ba.updated_at
FROM
    bank_accounts ba
    JOIN plaid_items pi ON ba.item_id = pi.id
WHERE
    pi.user_id = $1
ORDER BY ba.account_name
`

func (q *Queries) GetBankAccountsByUserID(ctx context.Context, userID uuid.UUID) ([]BankAccount, error) {
	rows, err := q.db.QueryContext(ctx, getBankAccountsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankAccount
	for rows.Next() {
		var i BankAccount
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.PlaidAccountID,
			&i.AccountName,
			&i.OfficialName,
			&i.AccountType,
			&i.AccountSubtype,
			&i.CurrentBalance,
			&i.AvailableBalance,
			&i.IsoCurrencyCode,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBankAccountBalance = `-- name: UpdateBankAccountBalance :exec
UPDATE bank_accounts
SET
    current_balance = $2,
    available_balance = $3,
    updated_at = now()
WHERE
    id = $1
`

type UpdateBankAccountBalanceParams struct {
	ID               uuid.UUID
	CurrentBalance   string
	AvailableBalance string
}

func (q *Queries) UpdateBankAccountBalance(ctx context.Context, arg UpdateBankAccountBalanceParams) error {
	_, err := q.db.ExecContext(ctx, updateBankAccountBalance, arg.ID, arg.CurrentBalance, arg.AvailableBalance)
	return err
}

const upsertBankAccount = `-- name: UpsertBankAccount :one
INSERT INTO
    bank_accounts (
        item_id,
        plaid_account_id,
        account_name,
        official_name,
        account_type,
        account_subtype,
        current_balance,
        available_balance,
        iso_currency_code
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9
    )
ON CONFLICT (plaid_account_id) DO UPDATE
    SET
        account_name = $3,
        official_name = $4,
        account_type = $5,
        account_subtype = $6,
        current_balance = $7,
        available_balance = $8,
        iso_currency_code = $9
RETURNING
    id, item_id, plaid_account_id, account_name, official_name, account_type, account_subtype, current_balance, available_balance, iso_currency_code, updated_at
`

type UpsertBankAccountParams struct {
	ItemID           uuid.UUID
	PlaidAccountID   string
	AccountName      string
	OfficialName     sql.NullString
	AccountType      string
	AccountSubtype   sql.NullString
	CurrentBalance   string
	AvailableBalance string
	IsoCurrencyCode  string
}

func (q *Queries) UpsertBankAccount(ctx context.Context, arg UpsertBankAccountParams) (BankAccount, error) {
	row := q.db.QueryRowContext(ctx, upsertBankAccount,
		arg.ItemID,
		arg.PlaidAccountID,
		arg.AccountName,
		arg.OfficialName,
		arg.AccountType,
		arg.AccountSubtype,
		arg.CurrentBalance,
		arg.AvailableBalance,
		arg.IsoCurrencyCode,
	)
	var i BankAccount
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.PlaidAccountID,
		&i.AccountName,
		&i.OfficialName,
		&i.AccountType,
		&i.AccountSubtype,
		&i.CurrentBalance,
		&i.AvailableBalance,
		&i.IsoCurrencyCode,
		&i.UpdatedAt,
	)
	return i, err
}
