// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bank_accounts.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBankAccount = `-- name: CreateBankAccount :one
INSERT INTO
    bank_accounts (
        plaid_account_id,
        plaid_item_id,
        account_name,
        official_name,
        account_type,
        account_subtype,
        current_balance,
        available_balance,
        iso_currency_code
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9
    )
RETURNING
    plaid_account_id, plaid_item_id, account_name, official_name, account_type, account_subtype, current_balance, available_balance, iso_currency_code, updated_at
`

type CreateBankAccountParams struct {
	PlaidAccountID   string
	PlaidItemID      string
	AccountName      string
	OfficialName     pgtype.Text
	AccountType      string
	AccountSubtype   pgtype.Text
	CurrentBalance   pgtype.Numeric
	AvailableBalance pgtype.Numeric
	IsoCurrencyCode  string
}

func (q *Queries) CreateBankAccount(ctx context.Context, arg CreateBankAccountParams) (BankAccount, error) {
	row := q.db.QueryRow(ctx, createBankAccount,
		arg.PlaidAccountID,
		arg.PlaidItemID,
		arg.AccountName,
		arg.OfficialName,
		arg.AccountType,
		arg.AccountSubtype,
		arg.CurrentBalance,
		arg.AvailableBalance,
		arg.IsoCurrencyCode,
	)
	var i BankAccount
	err := row.Scan(
		&i.PlaidAccountID,
		&i.PlaidItemID,
		&i.AccountName,
		&i.OfficialName,
		&i.AccountType,
		&i.AccountSubtype,
		&i.CurrentBalance,
		&i.AvailableBalance,
		&i.IsoCurrencyCode,
		&i.UpdatedAt,
	)
	return i, err
}

const getBankAccountByPlaidAccountID = `-- name: GetBankAccountByPlaidAccountID :one
SELECT plaid_account_id, plaid_item_id, account_name, official_name, account_type, account_subtype, current_balance, available_balance, iso_currency_code, updated_at FROM bank_accounts WHERE plaid_account_id = $1 LIMIT 1
`

func (q *Queries) GetBankAccountByPlaidAccountID(ctx context.Context, plaidAccountID string) (BankAccount, error) {
	row := q.db.QueryRow(ctx, getBankAccountByPlaidAccountID, plaidAccountID)
	var i BankAccount
	err := row.Scan(
		&i.PlaidAccountID,
		&i.PlaidItemID,
		&i.AccountName,
		&i.OfficialName,
		&i.AccountType,
		&i.AccountSubtype,
		&i.CurrentBalance,
		&i.AvailableBalance,
		&i.IsoCurrencyCode,
		&i.UpdatedAt,
	)
	return i, err
}

const getBankAccountsByItemID = `-- name: GetBankAccountsByItemID :many
SELECT plaid_account_id, plaid_item_id, account_name, official_name, account_type, account_subtype, current_balance, available_balance, iso_currency_code, updated_at
FROM bank_accounts
WHERE
    plaid_item_id = $1
ORDER BY account_name
`

func (q *Queries) GetBankAccountsByItemID(ctx context.Context, plaidItemID string) ([]BankAccount, error) {
	rows, err := q.db.Query(ctx, getBankAccountsByItemID, plaidItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankAccount
	for rows.Next() {
		var i BankAccount
		if err := rows.Scan(
			&i.PlaidAccountID,
			&i.PlaidItemID,
			&i.AccountName,
			&i.OfficialName,
			&i.AccountType,
			&i.AccountSubtype,
			&i.CurrentBalance,
			&i.AvailableBalance,
			&i.IsoCurrencyCode,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBankAccountsByUserID = `-- name: GetBankAccountsByUserID :many
SELECT ba.plaid_account_id, ba.plaid_item_id, ba.account_name, ba.official_name, ba.account_type, ba.account_subtype, ba.current_balance, ba.available_balance, ba.iso_currency_code, ba.updated_at
FROM
    bank_accounts ba
    JOIN plaid_items pli ON ba.plaid_item_id = pli.plaid_item_id
WHERE
    pli.app_user_id = $1
ORDER BY ba.account_name
`

func (q *Queries) GetBankAccountsByUserID(ctx context.Context, appUserID uuid.UUID) ([]BankAccount, error) {
	rows, err := q.db.Query(ctx, getBankAccountsByUserID, appUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankAccount
	for rows.Next() {
		var i BankAccount
		if err := rows.Scan(
			&i.PlaidAccountID,
			&i.PlaidItemID,
			&i.AccountName,
			&i.OfficialName,
			&i.AccountType,
			&i.AccountSubtype,
			&i.CurrentBalance,
			&i.AvailableBalance,
			&i.IsoCurrencyCode,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBankAccountBalance = `-- name: UpdateBankAccountBalance :exec
UPDATE bank_accounts
SET
    current_balance = $2,
    available_balance = $3,
    updated_at = now()
WHERE
    plaid_account_id = $1
`

type UpdateBankAccountBalanceParams struct {
	PlaidAccountID   string
	CurrentBalance   pgtype.Numeric
	AvailableBalance pgtype.Numeric
}

func (q *Queries) UpdateBankAccountBalance(ctx context.Context, arg UpdateBankAccountBalanceParams) error {
	_, err := q.db.Exec(ctx, updateBankAccountBalance, arg.PlaidAccountID, arg.CurrentBalance, arg.AvailableBalance)
	return err
}

const upsertBankAccount = `-- name: UpsertBankAccount :one
INSERT INTO
    bank_accounts (
        plaid_account_id,
        plaid_item_id,
        account_name,
        official_name,
        account_type,
        account_subtype,
        current_balance,
        available_balance,
        iso_currency_code
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9
    )
ON CONFLICT (plaid_account_id) DO UPDATE
    SET
        plaid_item_id = $2,
        account_name = $3,
        official_name = $4,
        account_type = $5,
        account_subtype = $6,
        current_balance = $7,
        available_balance = $8,
        iso_currency_code = $9,
        updated_at = now()
RETURNING
    plaid_account_id, plaid_item_id, account_name, official_name, account_type, account_subtype, current_balance, available_balance, iso_currency_code, updated_at
`

type UpsertBankAccountParams struct {
	PlaidAccountID   string
	PlaidItemID      string
	AccountName      string
	OfficialName     pgtype.Text
	AccountType      string
	AccountSubtype   pgtype.Text
	CurrentBalance   pgtype.Numeric
	AvailableBalance pgtype.Numeric
	IsoCurrencyCode  string
}

func (q *Queries) UpsertBankAccount(ctx context.Context, arg UpsertBankAccountParams) (BankAccount, error) {
	row := q.db.QueryRow(ctx, upsertBankAccount,
		arg.PlaidAccountID,
		arg.PlaidItemID,
		arg.AccountName,
		arg.OfficialName,
		arg.AccountType,
		arg.AccountSubtype,
		arg.CurrentBalance,
		arg.AvailableBalance,
		arg.IsoCurrencyCode,
	)
	var i BankAccount
	err := row.Scan(
		&i.PlaidAccountID,
		&i.PlaidItemID,
		&i.AccountName,
		&i.OfficialName,
		&i.AccountType,
		&i.AccountSubtype,
		&i.CurrentBalance,
		&i.AvailableBalance,
		&i.IsoCurrencyCode,
		&i.UpdatedAt,
	)
	return i, err
}
