// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: budgets.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBudget = `-- name: CreateBudget :one
INSERT INTO
    budgets (
        app_user_id,
        category,
        limit_amount,
        budget_period,
        start_date,
        end_date
    )
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
    id, app_user_id, category, limit_amount, amount_spent, budget_period, start_date, end_date, created_at
`

type CreateBudgetParams struct {
	AppUserID    uuid.UUID
	Category     string
	LimitAmount  pgtype.Numeric
	BudgetPeriod string
	StartDate    pgtype.Date
	EndDate      pgtype.Date
}

func (q *Queries) CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, createBudget,
		arg.AppUserID,
		arg.Category,
		arg.LimitAmount,
		arg.BudgetPeriod,
		arg.StartDate,
		arg.EndDate,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.AppUserID,
		&i.Category,
		&i.LimitAmount,
		&i.AmountSpent,
		&i.BudgetPeriod,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBudget = `-- name: DeleteBudget :exec
DELETE FROM budgets WHERE id = $1
`

func (q *Queries) DeleteBudget(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBudget, id)
	return err
}

const getBudgetByID = `-- name: GetBudgetByID :one
SELECT id, app_user_id, category, limit_amount, amount_spent, budget_period, start_date, end_date, created_at FROM budgets WHERE id = $1
`

func (q *Queries) GetBudgetByID(ctx context.Context, id uuid.UUID) (Budget, error) {
	row := q.db.QueryRow(ctx, getBudgetByID, id)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.AppUserID,
		&i.Category,
		&i.LimitAmount,
		&i.AmountSpent,
		&i.BudgetPeriod,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}

const getBudgetsByUserID = `-- name: GetBudgetsByUserID :many
SELECT id, app_user_id, category, limit_amount, amount_spent, budget_period, start_date, end_date, created_at FROM budgets WHERE app_user_id = $1 ORDER BY category
`

func (q *Queries) GetBudgetsByUserID(ctx context.Context, appUserID uuid.UUID) ([]Budget, error) {
	rows, err := q.db.Query(ctx, getBudgetsByUserID, appUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Budget
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.AppUserID,
			&i.Category,
			&i.LimitAmount,
			&i.AmountSpent,
			&i.BudgetPeriod,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBudgetAmountSpent = `-- name: UpdateBudgetAmountSpent :one
UPDATE budgets SET amount_spent = $2 WHERE id = $1 RETURNING id, app_user_id, category, limit_amount, amount_spent, budget_period, start_date, end_date, created_at
`

type UpdateBudgetAmountSpentParams struct {
	ID          uuid.UUID
	AmountSpent pgtype.Numeric
}

func (q *Queries) UpdateBudgetAmountSpent(ctx context.Context, arg UpdateBudgetAmountSpentParams) (Budget, error) {
	row := q.db.QueryRow(ctx, updateBudgetAmountSpent, arg.ID, arg.AmountSpent)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.AppUserID,
		&i.Category,
		&i.LimitAmount,
		&i.AmountSpent,
		&i.BudgetPeriod,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}
