// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package sqlcdb

import (
	"context"
)

// iteratorForCreateTransactions implements pgx.CopyFromSource.
type iteratorForCreateTransactions struct {
	rows                 []CreateTransactionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateTransactions) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateTransactions) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].PlaidTransactionID,
		r.rows[0].PlaidAccountID,
		r.rows[0].TransactionDate,
		r.rows[0].TransactionName,
		r.rows[0].Category,
		r.rows[0].Amount,
		r.rows[0].Pending,
	}, nil
}

func (r iteratorForCreateTransactions) Err() error {
	return nil
}

func (q *Queries) CreateTransactions(ctx context.Context, arg []CreateTransactionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"transactions"}, []string{"plaid_transaction_id", "plaid_account_id", "transaction_date", "transaction_name", "category", "amount", "pending"}, &iteratorForCreateTransactions{rows: arg})
}
