// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BankAccount struct {
	PlaidAccountID   string
	PlaidItemID      string
	AccountName      string
	OfficialName     pgtype.Text
	AccountType      string
	AccountSubtype   pgtype.Text
	CurrentBalance   pgtype.Numeric
	AvailableBalance pgtype.Numeric
	IsoCurrencyCode  string
	UpdatedAt        pgtype.Timestamptz
}

type Budget struct {
	ID           uuid.UUID
	AppUserID    uuid.UUID
	Category     string
	LimitAmount  pgtype.Numeric
	BudgetPeriod string
	StartDate    pgtype.Date
	EndDate      pgtype.Date
	CreatedAt    pgtype.Timestamptz
}

type PlaidItem struct {
	PlaidItemID      string
	AppUserID        uuid.UUID
	PlaidAccessToken string
	InstitutionName  string
	PlaidCursor      pgtype.Text
	LastSyncedAt     pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Transaction struct {
	PlaidTransactionID      string
	PlaidAccountID          string
	TransactionDate         pgtype.Date
	TransactionName         string
	Amount                  pgtype.Numeric
	Pending                 bool
	MerchantName            pgtype.Text
	LogoUrl                 pgtype.Text
	PersonalFinanceCategory pgtype.Text
	DetailedCategory        pgtype.Text
	CategoryConfidenceLevel pgtype.Text
	CategoryIconUrl         pgtype.Text
	CreatedAt               pgtype.Timestamptz
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}
