// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plaid_items.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPlaidItem = `-- name: CreatePlaidItem :one
INSERT INTO
    plaid_items (
        app_user_id,
        plaid_item_id,
        plaid_access_token,
        institution_name
    )
VALUES ($1, $2, $3, $4)
RETURNING
    plaid_item_id, app_user_id, plaid_access_token, institution_name, plaid_cursor, last_synced_at, created_at, updated_at
`

type CreatePlaidItemParams struct {
	AppUserID        uuid.UUID
	PlaidItemID      string
	PlaidAccessToken string
	InstitutionName  string
}

func (q *Queries) CreatePlaidItem(ctx context.Context, arg CreatePlaidItemParams) (PlaidItem, error) {
	row := q.db.QueryRow(ctx, createPlaidItem,
		arg.AppUserID,
		arg.PlaidItemID,
		arg.PlaidAccessToken,
		arg.InstitutionName,
	)
	var i PlaidItem
	err := row.Scan(
		&i.PlaidItemID,
		&i.AppUserID,
		&i.PlaidAccessToken,
		&i.InstitutionName,
		&i.PlaidCursor,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCursor = `-- name: GetCursor :one
SELECT plaid_cursor FROM plaid_items WHERE plaid_item_id = $1 LIMIT 1
`

func (q *Queries) GetCursor(ctx context.Context, plaidItemID string) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getCursor, plaidItemID)
	var plaid_cursor pgtype.Text
	err := row.Scan(&plaid_cursor)
	return plaid_cursor, err
}

const getPlaidItemByID = `-- name: GetPlaidItemByID :one
SELECT plaid_item_id, app_user_id, plaid_access_token, institution_name, plaid_cursor, last_synced_at, created_at, updated_at FROM plaid_items WHERE plaid_item_id = $1
`

func (q *Queries) GetPlaidItemByID(ctx context.Context, plaidItemID string) (PlaidItem, error) {
	row := q.db.QueryRow(ctx, getPlaidItemByID, plaidItemID)
	var i PlaidItem
	err := row.Scan(
		&i.PlaidItemID,
		&i.AppUserID,
		&i.PlaidAccessToken,
		&i.InstitutionName,
		&i.PlaidCursor,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlaidItemByPlaidItemID = `-- name: GetPlaidItemByPlaidItemID :one
SELECT plaid_item_id, app_user_id, plaid_access_token, institution_name, plaid_cursor, last_synced_at, created_at, updated_at FROM plaid_items WHERE plaid_item_id = $1 LIMIT 1
`

func (q *Queries) GetPlaidItemByPlaidItemID(ctx context.Context, plaidItemID string) (PlaidItem, error) {
	row := q.db.QueryRow(ctx, getPlaidItemByPlaidItemID, plaidItemID)
	var i PlaidItem
	err := row.Scan(
		&i.PlaidItemID,
		&i.AppUserID,
		&i.PlaidAccessToken,
		&i.InstitutionName,
		&i.PlaidCursor,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlaidItemsByUserID = `-- name: GetPlaidItemsByUserID :many
SELECT plaid_item_id, app_user_id, plaid_access_token, institution_name, plaid_cursor, last_synced_at, created_at, updated_at
FROM plaid_items
WHERE
    app_user_id = $1
ORDER BY institution_name
`

func (q *Queries) GetPlaidItemsByUserID(ctx context.Context, appUserID uuid.UUID) ([]PlaidItem, error) {
	rows, err := q.db.Query(ctx, getPlaidItemsByUserID, appUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlaidItem
	for rows.Next() {
		var i PlaidItem
		if err := rows.Scan(
			&i.PlaidItemID,
			&i.AppUserID,
			&i.PlaidAccessToken,
			&i.InstitutionName,
			&i.PlaidCursor,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlaidItemCursor = `-- name: UpdatePlaidItemCursor :exec
UPDATE plaid_items
SET
    plaid_cursor = $2,
    last_synced_at = now(),
    updated_at = now()
WHERE
    plaid_item_id = $1
`

type UpdatePlaidItemCursorParams struct {
	PlaidItemID string
	PlaidCursor pgtype.Text
}

func (q *Queries) UpdatePlaidItemCursor(ctx context.Context, arg UpdatePlaidItemCursorParams) error {
	_, err := q.db.Exec(ctx, updatePlaidItemCursor, arg.PlaidItemID, arg.PlaidCursor)
	return err
}
