// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO
    transactions (
        plaid_transaction_id,
        plaid_account_id,
        transaction_date,
        transaction_name,
        amount,
        pending,
        merchant_name,
        logo_url,
        personal_finance_category,
        detailed_category,
        category_confidence_level,
        category_icon_url
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12
    )
RETURNING
    plaid_transaction_id, plaid_account_id, transaction_date, transaction_name, amount, pending, merchant_name, logo_url, personal_finance_category, detailed_category, category_confidence_level, category_icon_url, created_at
`

type CreateTransactionParams struct {
	PlaidTransactionID      string
	PlaidAccountID          string
	TransactionDate         pgtype.Date
	TransactionName         string
	Amount                  pgtype.Numeric
	Pending                 bool
	MerchantName            pgtype.Text
	LogoUrl                 pgtype.Text
	PersonalFinanceCategory pgtype.Text
	DetailedCategory        pgtype.Text
	CategoryConfidenceLevel pgtype.Text
	CategoryIconUrl         pgtype.Text
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.PlaidTransactionID,
		arg.PlaidAccountID,
		arg.TransactionDate,
		arg.TransactionName,
		arg.Amount,
		arg.Pending,
		arg.MerchantName,
		arg.LogoUrl,
		arg.PersonalFinanceCategory,
		arg.DetailedCategory,
		arg.CategoryConfidenceLevel,
		arg.CategoryIconUrl,
	)
	var i Transaction
	err := row.Scan(
		&i.PlaidTransactionID,
		&i.PlaidAccountID,
		&i.TransactionDate,
		&i.TransactionName,
		&i.Amount,
		&i.Pending,
		&i.MerchantName,
		&i.LogoUrl,
		&i.PersonalFinanceCategory,
		&i.DetailedCategory,
		&i.CategoryConfidenceLevel,
		&i.CategoryIconUrl,
		&i.CreatedAt,
	)
	return i, err
}

type CreateTransactionsParams struct {
	PlaidTransactionID      string
	PlaidAccountID          string
	TransactionDate         pgtype.Date
	TransactionName         string
	Amount                  pgtype.Numeric
	Pending                 bool
	MerchantName            pgtype.Text
	LogoUrl                 pgtype.Text
	PersonalFinanceCategory pgtype.Text
	DetailedCategory        pgtype.Text
	CategoryConfidenceLevel pgtype.Text
	CategoryIconUrl         pgtype.Text
}

const getTransactionsByAccountID = `-- name: GetTransactionsByAccountID :many
SELECT plaid_transaction_id, plaid_account_id, transaction_date, transaction_name, amount, pending, merchant_name, logo_url, personal_finance_category, detailed_category, category_confidence_level, category_icon_url, created_at
FROM transactions
WHERE
    plaid_account_id = $1
ORDER BY transaction_date DESC
`

func (q *Queries) GetTransactionsByAccountID(ctx context.Context, plaidAccountID string) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByAccountID, plaidAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.PlaidTransactionID,
			&i.PlaidAccountID,
			&i.TransactionDate,
			&i.TransactionName,
			&i.Amount,
			&i.Pending,
			&i.MerchantName,
			&i.LogoUrl,
			&i.PersonalFinanceCategory,
			&i.DetailedCategory,
			&i.CategoryConfidenceLevel,
			&i.CategoryIconUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByUserID = `-- name: GetTransactionsByUserID :many
SELECT t.plaid_transaction_id, t.plaid_account_id, t.transaction_date, t.transaction_name, t.amount, t.pending, t.merchant_name, t.logo_url, t.personal_finance_category, t.detailed_category, t.category_confidence_level, t.category_icon_url, t.created_at
FROM
    transactions t
    JOIN bank_accounts ba ON t.plaid_account_id = ba.plaid_account_id
    JOIN plaid_items pli ON ba.plaid_item_id = pli.plaid_item_id
WHERE
    pli.app_user_id = $1
ORDER BY t.transaction_date DESC
`

func (q *Queries) GetTransactionsByUserID(ctx context.Context, appUserID uuid.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByUserID, appUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.PlaidTransactionID,
			&i.PlaidAccountID,
			&i.TransactionDate,
			&i.TransactionName,
			&i.Amount,
			&i.Pending,
			&i.MerchantName,
			&i.LogoUrl,
			&i.PersonalFinanceCategory,
			&i.DetailedCategory,
			&i.CategoryConfidenceLevel,
			&i.CategoryIconUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTransaction = `-- name: UpsertTransaction :one
INSERT INTO
    transactions (
        plaid_transaction_id,
        plaid_account_id,
        transaction_date,
        transaction_name,
        amount,
        pending,
        merchant_name,
        logo_url,
        personal_finance_category,
        detailed_category,
        category_confidence_level,
        category_icon_url
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12
    )
ON CONFLICT (plaid_transaction_id) DO
UPDATE
SET
    transaction_date = EXCLUDED.transaction_date,
    transaction_name = EXCLUDED.transaction_name,
    amount = EXCLUDED.amount,
    pending = EXCLUDED.pending,
    merchant_name = EXCLUDED.merchant_name,
    logo_url = EXCLUDED.logo_url,
    personal_finance_category = EXCLUDED.personal_finance_category,
    detailed_category = EXCLUDED.detailed_category,
    category_confidence_level = EXCLUDED.category_confidence_level,
    category_icon_url = EXCLUDED.category_icon_url
RETURNING
    plaid_transaction_id, plaid_account_id, transaction_date, transaction_name, amount, pending, merchant_name, logo_url, personal_finance_category, detailed_category, category_confidence_level, category_icon_url, created_at
`

type UpsertTransactionParams struct {
	PlaidTransactionID      string
	PlaidAccountID          string
	TransactionDate         pgtype.Date
	TransactionName         string
	Amount                  pgtype.Numeric
	Pending                 bool
	MerchantName            pgtype.Text
	LogoUrl                 pgtype.Text
	PersonalFinanceCategory pgtype.Text
	DetailedCategory        pgtype.Text
	CategoryConfidenceLevel pgtype.Text
	CategoryIconUrl         pgtype.Text
}

func (q *Queries) UpsertTransaction(ctx context.Context, arg UpsertTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, upsertTransaction,
		arg.PlaidTransactionID,
		arg.PlaidAccountID,
		arg.TransactionDate,
		arg.TransactionName,
		arg.Amount,
		arg.Pending,
		arg.MerchantName,
		arg.LogoUrl,
		arg.PersonalFinanceCategory,
		arg.DetailedCategory,
		arg.CategoryConfidenceLevel,
		arg.CategoryIconUrl,
	)
	var i Transaction
	err := row.Scan(
		&i.PlaidTransactionID,
		&i.PlaidAccountID,
		&i.TransactionDate,
		&i.TransactionName,
		&i.Amount,
		&i.Pending,
		&i.MerchantName,
		&i.LogoUrl,
		&i.PersonalFinanceCategory,
		&i.DetailedCategory,
		&i.CategoryConfidenceLevel,
		&i.CategoryIconUrl,
		&i.CreatedAt,
	)
	return i, err
}
