// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO
    transactions (
        plaid_transaction_id,
        plaid_account_id,
        transaction_date,
        transaction_name,
        category,
        amount,
        pending
    )
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING
    plaid_transaction_id, plaid_account_id, transaction_date, transaction_name, category, amount, pending, created_at
`

type CreateTransactionParams struct {
	PlaidTransactionID string
	PlaidAccountID     string
	TransactionDate    pgtype.Date
	TransactionName    string
	Category           string
	Amount             pgtype.Numeric
	Pending            bool
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.PlaidTransactionID,
		arg.PlaidAccountID,
		arg.TransactionDate,
		arg.TransactionName,
		arg.Category,
		arg.Amount,
		arg.Pending,
	)
	var i Transaction
	err := row.Scan(
		&i.PlaidTransactionID,
		&i.PlaidAccountID,
		&i.TransactionDate,
		&i.TransactionName,
		&i.Category,
		&i.Amount,
		&i.Pending,
		&i.CreatedAt,
	)
	return i, err
}

type CreateTransactionsParams struct {
	PlaidTransactionID string
	PlaidAccountID     string
	TransactionDate    pgtype.Date
	TransactionName    string
	Category           string
	Amount             pgtype.Numeric
	Pending            bool
}

const getTransactionsByAccountID = `-- name: GetTransactionsByAccountID :many
SELECT plaid_transaction_id, plaid_account_id, transaction_date, transaction_name, category, amount, pending, created_at
FROM transactions
WHERE
    plaid_account_id = $1
ORDER BY transaction_date DESC
`

func (q *Queries) GetTransactionsByAccountID(ctx context.Context, plaidAccountID string) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByAccountID, plaidAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.PlaidTransactionID,
			&i.PlaidAccountID,
			&i.TransactionDate,
			&i.TransactionName,
			&i.Category,
			&i.Amount,
			&i.Pending,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByUserID = `-- name: GetTransactionsByUserID :many
SELECT t.plaid_transaction_id, t.plaid_account_id, t.transaction_date, t.transaction_name, t.category, t.amount, t.pending, t.created_at
FROM
    transactions t
    JOIN bank_accounts ba ON t.plaid_account_id = ba.plaid_account_id
    JOIN plaid_items pli ON ba.plaid_item_id = pli.plaid_item_id
WHERE
    pli.app_user_id = $1
ORDER BY t.transaction_date DESC
`

func (q *Queries) GetTransactionsByUserID(ctx context.Context, appUserID uuid.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByUserID, appUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.PlaidTransactionID,
			&i.PlaidAccountID,
			&i.TransactionDate,
			&i.TransactionName,
			&i.Category,
			&i.Amount,
			&i.Pending,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTransaction = `-- name: UpsertTransaction :one
INSERT INTO
    transactions (
        plaid_transaction_id,
        plaid_account_id,
        transaction_date,
        transaction_name,
        category,
        amount,
        pending
    )
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (plaid_transaction_id) DO
UPDATE
SET
    transaction_date = EXCLUDED.transaction_date,
    transaction_name = EXCLUDED.transaction_name,
    category = EXCLUDED.category,
    amount = EXCLUDED.amount,
    pending = EXCLUDED.pending
RETURNING
    plaid_transaction_id, plaid_account_id, transaction_date, transaction_name, category, amount, pending, created_at
`

type UpsertTransactionParams struct {
	PlaidTransactionID string
	PlaidAccountID     string
	TransactionDate    pgtype.Date
	TransactionName    string
	Category           string
	Amount             pgtype.Numeric
	Pending            bool
}

func (q *Queries) UpsertTransaction(ctx context.Context, arg UpsertTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, upsertTransaction,
		arg.PlaidTransactionID,
		arg.PlaidAccountID,
		arg.TransactionDate,
		arg.TransactionName,
		arg.Category,
		arg.Amount,
		arg.Pending,
	)
	var i Transaction
	err := row.Scan(
		&i.PlaidTransactionID,
		&i.PlaidAccountID,
		&i.TransactionDate,
		&i.TransactionName,
		&i.Category,
		&i.Amount,
		&i.Pending,
		&i.CreatedAt,
	)
	return i, err
}
